// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelaxService.Data;

#nullable disable

namespace RelaxService.Migrations
{
    [DbContext(typeof(SpotDbContext))]
    [Migration("20240529090735_keyword Sheet")]
    partial class keywordSheet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RelaxService.Models.AdsClick", b =>
                {
                    b.Property<int>("AdsClickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdsClickId"));

                    b.Property<DateTime>("AdsClickTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("AdsId")
                        .HasColumnType("int");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Device")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("memberId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AdsClickId");

                    b.ToTable("AdsClick");
                });

            modelBuilder.Entity("RelaxService.Models.AdsDetailM", b =>
                {
                    b.Property<int>("AdsDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdsDId"));

                    b.Property<int?>("AdsClick")
                        .HasColumnType("int");

                    b.Property<int>("AnalysisId")
                        .HasColumnType("int");

                    b.Property<string>("ClickMemberId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LikeClick")
                        .HasColumnType("int");

                    b.Property<string>("UserIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("adsId")
                        .HasColumnType("int");

                    b.HasKey("AdsDId");

                    b.ToTable("AdsDetailM");
                });

            modelBuilder.Entity("RelaxService.Models.AdsDetailN", b =>
                {
                    b.Property<int>("AdsDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdsDId"));

                    b.Property<int?>("AdsClick")
                        .HasColumnType("int");

                    b.Property<int>("AnalysisId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LikeClick")
                        .HasColumnType("int");

                    b.Property<string>("UserIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("adsId")
                        .HasColumnType("int");

                    b.HasKey("AdsDId");

                    b.ToTable("AdsDetailN");
                });

            modelBuilder.Entity("RelaxService.Models.AdsLike", b =>
                {
                    b.Property<int>("AdsLikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdsLikeId"));

                    b.Property<int>("AdsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AdsLikeTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Device")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("memberId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AdsLikeId");

                    b.ToTable("AdsLike");
                });

            modelBuilder.Entity("RelaxService.Models.Advertisements", b =>
                {
                    b.Property<int>("AdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdId"));

                    b.Property<int?>("AdLoved")
                        .HasColumnType("int");

                    b.Property<string>("AdUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Clicks")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("tripId")
                        .HasColumnType("int");

                    b.HasKey("AdId");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("RelaxService.Models.Analysis", b =>
                {
                    b.Property<int>("AnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnalysisId"));

                    b.Property<int?>("AdsDesktop")
                        .HasColumnType("int");

                    b.Property<int?>("AdsMobile")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EnterDesktop")
                        .HasColumnType("int");

                    b.Property<int?>("EnterMobile")
                        .HasColumnType("int");

                    b.Property<int?>("LikeDesktop")
                        .HasColumnType("int");

                    b.Property<int?>("LikeMobile")
                        .HasColumnType("int");

                    b.Property<int?>("SearchDesktop")
                        .HasColumnType("int");

                    b.Property<int?>("SearchMobile")
                        .HasColumnType("int");

                    b.Property<int?>("TotalAds")
                        .HasColumnType("int");

                    b.Property<int?>("TotalEnter")
                        .HasColumnType("int");

                    b.Property<int?>("TotalLike")
                        .HasColumnType("int");

                    b.Property<int?>("TotalSearch")
                        .HasColumnType("int");

                    b.Property<int?>("TotalUser")
                        .HasColumnType("int");

                    b.HasKey("AnalysisId");

                    b.ToTable("Analysis");
                });

            modelBuilder.Entity("RelaxService.Models.AnalysisDetailM", b =>
                {
                    b.Property<int>("AnalysisDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnalysisDId"));

                    b.Property<int?>("AdsClicks")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LikeClicks")
                        .HasColumnType("int");

                    b.Property<int?>("SearchClicks")
                        .HasColumnType("int");

                    b.Property<int>("analysisId")
                        .HasColumnType("int");

                    b.Property<string>("memberId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AnalysisDId");

                    b.ToTable("AnalysisDetailM");
                });

            modelBuilder.Entity("RelaxService.Models.AnalysisDetailN", b =>
                {
                    b.Property<int>("AnalysisDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnalysisDId"));

                    b.Property<int?>("AdsClicks")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LikeClicks")
                        .HasColumnType("int");

                    b.Property<int?>("SearchClicks")
                        .HasColumnType("int");

                    b.Property<string>("UserIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("analysisId")
                        .HasColumnType("int");

                    b.HasKey("AnalysisDId");

                    b.ToTable("AnalysisDetailN");
                });

            modelBuilder.Entity("RelaxService.Models.Attractions", b =>
                {
                    b.Property<int>("AttractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttractionId"));

                    b.Property<string>("AttractionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EstimatedStayTime")
                        .HasColumnType("int");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Tag")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TimeCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("XCoordinate")
                        .HasColumnType("int");

                    b.Property<int?>("YCoordinate")
                        .HasColumnType("int");

                    b.Property<string>("memberId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AttractionId");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("RelaxService.Models.EnterHome", b =>
                {
                    b.Property<int>("EnterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnterId"));

                    b.Property<string>("EnterDevice")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EnterPage")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("EnterTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublicIp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("memberId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EnterId");

                    b.ToTable("EnterHome");
                });

            modelBuilder.Entity("RelaxService.Models.GenderAds", b =>
                {
                    b.Property<int>("GenderAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderAId"));

                    b.Property<int?>("Age18")
                        .HasColumnType("int");

                    b.Property<int?>("Age25")
                        .HasColumnType("int");

                    b.Property<int?>("Age35")
                        .HasColumnType("int");

                    b.Property<int?>("Age45")
                        .HasColumnType("int");

                    b.Property<int?>("Age65")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GenderAId");

                    b.ToTable("GenderAds");
                });

            modelBuilder.Entity("RelaxService.Models.GenderAdsLike", b =>
                {
                    b.Property<int>("GenderALId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderALId"));

                    b.Property<int?>("Age18")
                        .HasColumnType("int");

                    b.Property<int?>("Age25")
                        .HasColumnType("int");

                    b.Property<int?>("Age35")
                        .HasColumnType("int");

                    b.Property<int?>("Age45")
                        .HasColumnType("int");

                    b.Property<int?>("Age65")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GenderALId");

                    b.ToTable("GenderAdsLike");
                });

            modelBuilder.Entity("RelaxService.Models.GenderSearch", b =>
                {
                    b.Property<int>("GenderSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderSId"));

                    b.Property<int?>("Age18")
                        .HasColumnType("int");

                    b.Property<int?>("Age25")
                        .HasColumnType("int");

                    b.Property<int?>("Age35")
                        .HasColumnType("int");

                    b.Property<int?>("Age45")
                        .HasColumnType("int");

                    b.Property<int?>("Age65")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GenderSId");

                    b.ToTable("GenderSearch");
                });

            modelBuilder.Entity("RelaxService.Models.Keyword", b =>
                {
                    b.Property<int>("KeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeywordId"));

                    b.Property<DateTime?>("DataDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Keyname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("KeywordId");

                    b.ToTable("Keyword");
                });

            modelBuilder.Entity("RelaxService.Models.Search", b =>
                {
                    b.Property<int>("SearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SearchId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Device")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Keywords")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SearchIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SearchTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("memberId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SearchId");

                    b.ToTable("Search");
                });
#pragma warning restore 612, 618
        }
    }
}
